name: nekopedia_temp
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.3.0
  smooth_star_rating_null_safety: ^1.0.4+2
  shared_preferences: ^2.0.17
  http: ^0.13.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/_emptyPaw.png
    - assets/images/_fullPaw.png
    - assets/images/_placeholder.jpg
    - assets/images/_logo.png
    - assets/images/_buttonlogo.png
    - assets/images/Abyssinian.JPG
    - assets/images/Aegean.JPG
    - assets/images/American Bobtail.JPG
    - assets/images/American Curl.JPG
    - assets/images/American Shorthair.JPG
    - assets/images/American Wirehair.JPG
    - assets/images/Arabian Mau.JPG
    - assets/images/Australian Mist.JPG
    - assets/images/Balinese.JPG
    - assets/images/Bambino.JPG
    - assets/images/Bengal.JPG
    - assets/images/Birman.JPG
    - assets/images/Bombay.JPG
    - assets/images/British Longhair.JPG
    - assets/images/British Shorthair.JPG
    - assets/images/Burmese.JPG
    - assets/images/Burmilla.JPG
    - assets/images/California Spangled.JPG
    - assets/images/Chantilly-Tiffany.JPG
    - assets/images/Chartreux.JPG
    - assets/images/Chausie.JPG
    - assets/images/Cheetoh.JPG
    - assets/images/Colorpoint Shorthair.JPG
    - assets/images/Cornish Rex.JPG
    - assets/images/Cymric.JPG
    - assets/images/Cyprus.JPG
    - assets/images/Devon Rex.JPG
    - assets/images/Donskoy.JPG
    - assets/images/Dragon Li.JPG
    - assets/images/Egyptian Mau.JPG
    - assets/images/European Burmese.JPG
    - assets/images/Exotic Shorthair.JPG
    - assets/images/Havana Brown.JPG
    - assets/images/Himalayan.JPG
    - assets/images/Japanese Bobtail.JPG
    - assets/images/Javanese.JPG
    - assets/images/Khao Manee.JPG
    - assets/images/Korat.JPG
    - assets/images/Kurilian.JPG
    - assets/images/LaPerm.JPG
    - assets/images/Maine Coon.JPG
    - assets/images/Malayan.JPG
    - assets/images/Manx.JPG
    - assets/images/Munchkin.JPG
    - assets/images/Nebelung.JPG
    - assets/images/Norwegian Forest Cat.JPG
    - assets/images/Ocicat.JPG
    - assets/images/Oriental.JPG
    - assets/images/Persian.JPG
    - assets/images/Pixie-bob.JPG
    - assets/images/Ragamuffin.JPG
    - assets/images/Ragdoll.JPG
    - assets/images/Russian Blue.JPG
    - assets/images/Savannah.JPG
    - assets/images/Scottish Fold.JPG
    - assets/images/Selkirk Rex.JPG
    - assets/images/Siamese.JPG
    - assets/images/Siberian.JPG
    - assets/images/Singapura.JPG
    - assets/images/Snowshoe.JPG
    - assets/images/Somali.JPG
    - assets/images/Sphynx.JPG
    - assets/images/Tonkinese.JPG
    - assets/images/Toyger.JPG
    - assets/images/Turkish Angora.JPG
    - assets/images/Turkish Van.JPG
    - assets/images/York Chocolate.JPG

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Creamy_Garden
      fonts:
        - asset: assets/fonts/Creamy_Garden_Regular.ttf

    - family: Oliver
      fonts:
        - asset: assets/fonts/Oliver-Regular.ttf

    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf